# Loop
max_iters: 50
hamiltonian_convergence_eps: 1e-4
density_convergence_eps: 1e-3
verbose: True

# MPI settings
exe: /home2/rong/00.Development/0.GitHub/8.KS-DFT_local/siesta
num_procs: 4

# Problem to solve
problem: molecular/0001
